# Generated by Django 6.0.6 on 2026-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='encrypted_key',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
