# Generated by Django 6.0.6 on 2026-07-07 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_create_hidden_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.TextField(blank=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=1)),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_login_at'],
            },
        ),
    ]
